log:
  disable_sentry: true
  level: info

keys:
  signer: "S_SOME_SECRET_KEY"
  source: "G_SOME_PUBLIC_KEY"

horizon:
  url: "http://horizon"

client:
  endpoint: "http://horizon"

submit:
  endpoint: "http://horizon"

listener:
  addr: :8181

cop:
  disabled: true